# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/benjamin/Documents/git/ImageAnalysisAssignment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/benjamin/Documents/git/ImageAnalysisAssignment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benjamin/Documents/git/ImageAnalysisAssignment/CMakeFiles /home/benjamin/Documents/git/ImageAnalysisAssignment/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benjamin/Documents/git/ImageAnalysisAssignment/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named modelsCreator

# Build rule for target.
modelsCreator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modelsCreator
.PHONY : modelsCreator

# fast build rule for target.
modelsCreator/fast:
	$(MAKE) -f CMakeFiles/modelsCreator.dir/build.make CMakeFiles/modelsCreator.dir/build
.PHONY : modelsCreator/fast

#=============================================================================
# Target rules for targets named imageDecision

# Build rule for target.
imageDecision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imageDecision
.PHONY : imageDecision

# fast build rule for target.
imageDecision/fast:
	$(MAKE) -f CMakeFiles/imageDecision.dir/build.make CMakeFiles/imageDecision.dir/build
.PHONY : imageDecision/fast

src/modelMaker/makeModels.o: src/modelMaker/makeModels.cpp.o

.PHONY : src/modelMaker/makeModels.o

# target to build an object file
src/modelMaker/makeModels.cpp.o:
	$(MAKE) -f CMakeFiles/modelsCreator.dir/build.make CMakeFiles/modelsCreator.dir/src/modelMaker/makeModels.cpp.o
.PHONY : src/modelMaker/makeModels.cpp.o

src/modelMaker/makeModels.i: src/modelMaker/makeModels.cpp.i

.PHONY : src/modelMaker/makeModels.i

# target to preprocess a source file
src/modelMaker/makeModels.cpp.i:
	$(MAKE) -f CMakeFiles/modelsCreator.dir/build.make CMakeFiles/modelsCreator.dir/src/modelMaker/makeModels.cpp.i
.PHONY : src/modelMaker/makeModels.cpp.i

src/modelMaker/makeModels.s: src/modelMaker/makeModels.cpp.s

.PHONY : src/modelMaker/makeModels.s

# target to generate assembly for a file
src/modelMaker/makeModels.cpp.s:
	$(MAKE) -f CMakeFiles/modelsCreator.dir/build.make CMakeFiles/modelsCreator.dir/src/modelMaker/makeModels.cpp.s
.PHONY : src/modelMaker/makeModels.cpp.s

src/solver/main.o: src/solver/main.cpp.o

.PHONY : src/solver/main.o

# target to build an object file
src/solver/main.cpp.o:
	$(MAKE) -f CMakeFiles/imageDecision.dir/build.make CMakeFiles/imageDecision.dir/src/solver/main.cpp.o
.PHONY : src/solver/main.cpp.o

src/solver/main.i: src/solver/main.cpp.i

.PHONY : src/solver/main.i

# target to preprocess a source file
src/solver/main.cpp.i:
	$(MAKE) -f CMakeFiles/imageDecision.dir/build.make CMakeFiles/imageDecision.dir/src/solver/main.cpp.i
.PHONY : src/solver/main.cpp.i

src/solver/main.s: src/solver/main.cpp.s

.PHONY : src/solver/main.s

# target to generate assembly for a file
src/solver/main.cpp.s:
	$(MAKE) -f CMakeFiles/imageDecision.dir/build.make CMakeFiles/imageDecision.dir/src/solver/main.cpp.s
.PHONY : src/solver/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... modelsCreator"
	@echo "... imageDecision"
	@echo "... src/modelMaker/makeModels.o"
	@echo "... src/modelMaker/makeModels.i"
	@echo "... src/modelMaker/makeModels.s"
	@echo "... src/solver/main.o"
	@echo "... src/solver/main.i"
	@echo "... src/solver/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

